version: '2.1'
services:
  sa-api-apollo:
    build: .
    environment:
      PORT: '5001'
      SHOW_URLS: 'true'
      AUTH_URL: 'http://ec2-54-158-114-74.compute-1.amazonaws.com'
      AUTH_PORT: '4000'
      AUTH_USERS_ENTRY: 'sa-auth-ms/resources/'
    ports:
      - '5001:5001'
